### ISSUE TITLE
Create the Presentation and Presentation slide deck

### ISSUE THREAD

**Issue by sanjelgrob** [AngryMonkeysManagingInADigitalWorld/ISQA3420#10]

**Comment by ProfX1019** [comment]
Have you emailed Mr. Germonprez on whether the presentation is basically putting the GitHub documentation into a power point presentation? Thanks.

**Comment by sanjelgrob** [comment]
No I have not. I will do that this afternoon. I am trying to figure out what to put in the manifest and policy right now.

**Comment by ProfX1019** [comment]
Please let me know if you need any help. I will email him and cc you.

**Comment by ProfX1019** [comment]
In watching the video, not much was really said about the presentation slides. Do you think we're just transferring the deliverables into power point slides or are we supposed to create more of a professional looking presentation? How are you doing yours? Thanks.

**Comment by sanjelgrob** [comment]
I am not yet sure how to approach this. Looking at the example provided, we just need to put texts in them but I will have him review it first though when done.

**Comment by ProfX1019** [comment]
Sounds good.
