### ISSUE TITLE
Slides - ERD, DFD

### ISSUE THREAD

**Issue by ProfX1019** [AngryMonkeysManagingInADigitalWorld/ISQA3420#37]
I will work on them tonight. Probably after our meeting with the instructor. Thanks.

**Comment by ProfX1019** [comment]
Please let me know if you need me to do anything. Thanks.

**Comment by sanjelgrob** [comment]
Just try to get your commits up.

**Comment by ProfX1019** [comment]
Hopefully adding the slides will help. I thought we needed about 60 commits as a group.

**Comment by sanjelgrob** [comment]
Yeh, I just saw your commit rate. I have to catch up to you then.
