### ISSUE TITLE
Data Flow Diagram Dictionary

### ISSUE THREAD

**Issue by ProfX1019** [AngryMonkeysManagingInADigitalWorld/ISQA3420#7]
Corporate Developer

Corporate Manager

CPE Information

CPE Request

CPE Response

File License and CPE Information

File SHA 1 Request - Hash of file

File SHA 1  Response - A yes/no response as to whether or not the hash of a file exist in the database.

File/Package

License Information - Obligations set forth by owners of a particular work – such as software – that govern the use of their work.

Manage Code Information

Manage Project

National Vulnerability Database

NIST CPE Information

Package Information

Package Query - Request for software project (comprised of many packages).

Project File

Project Information Request

Project Information Response

SPDX DB

Version Control/Field System

**Comment by sanjelgrob** [comment]
The initial placeholder has been created.
